# Change these first
owner: sbesson # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: OME website
    url: https://www.openmicroscopy.org
  - name: OME website (alias)
    url: https://openmicroscopy.org
  - name: OME website (legacy)
    url: https://www-legacy.openmicroscopy.org
  - name: OME blog (redirected)
    url: https://blog.openmicroscopy.org
  - name: OME NGFF
    url: https://ngff.openmicroscopy.org
  - name: OME forum (legacy)
    url: https://phpbb.openmicroscopy.org
  - name: OMERO figure static website (redirected)
    url: https://figure.openmicroscopy.org
  - name: OME help (redirected)
    url: https://help.openmicroscopy.org
  - name: OME contributing
    url: https://ome-contributing.readthedocs.io/en/latest/
  - name: OME contributing (redirected)
    url: https://www.openmicroscopy.org/site/support/contributing/
  - name: OME artifactory
    url: https://artifacts.openmicroscopy.org
  - name: OME downloads
    url: https://downloads.openmicroscopy.org
  - name: OME documentation
    url: https://docs.openmicroscopy.org
  - name: OME demo server
    url: https://demo.openmicroscopy.org
  - name: OME XSD schemas
    url: http://www.openmicroscopy.org/Schemas
  - name: OME CI server (legacy)
    url: https://ci.openmicroscopy.org
  - name: OME CI server (merge)
    url: https://merge-ci.openmicroscopy.org/jenkins
  - name: OME CI server (latest)
    url: https://latest-ci.openmicroscopy.org/jenkins
  - name: OME training server 1
    url: https://outreach.openmicroscopy.org
  - name: OME issue tracking system (legacy)
    url: https://trac.openmicroscopy.org
  - name: OME trac OMERO API (redirected)
    url: https://trac.openmicroscopy.org.uk/ome/wiki/OmeroApi
  - name: OME file formats (redirected)
    url: http://www.openmicroscopy.org/site/support/file-formats
  - name: OME units documentation (redirected)
    url:  https://www.openmicroscopy.org/site/support/ome-model/developers/ome-units.html
  - name: OME training server 2
    url: https://workshop.openmicroscopy.org
  - name: OME Q&A
    url: http://qa.openmicroscopy.org.uk/
  - name: OME GitHub
    url: https://github.com/ome
  - name: OME gate (22)
    check: "tcp-ping"
    url: $OME_GATE
    port: 22
  - name: OME gate (443)
    check: "tcp-ping"
    url: $OME_GATE
    port: 443
  - name: UoD SLS OMERO (authenticated)
    url: https://nightshade.openmicroscopy.org
  - name: UoD SLS OMERO (public)
    url: https://omero.lifesci.dundee.ac.uk
  - name: UoD SLS OMERO (image 3925540 - render_thumbnail)
    url: https://omero.lifesci.dundee.ac.uk/webgateway/render_thumbnail/3925540/
  - name: UoD SLS OMERO (image 3925540 - render_image)
    url: https://omero.lifesci.dundee.ac.uk/webgateway/render_image/3925540/3/5/
  - name: UoD SLS OMERO (image 3925540 - img_detail)
    url: https://omero.lifesci.dundee.ac.uk/webgateway/img_detail/3925540/
  - name: UoD SLS OMERO (10.17867/10000109)
    url: http://dx.doi.org/10.17867/10000109
  - name: UoD teaching OMERO
    url: https://learning.openmicroscopy.org
  - name: IDR
    url: https://idr.openmicroscopy.org
  - name: IDR FTP
    check: "tcp-ping"
    url: idr-ftp.openmicroscopy.org
    port: 21
  - name: ITR
    url: https://itr.openmicroscopy.org
  - name: IDR API
    url: https://idr.openmicroscopy.org/about/api.html
  - name: IDR submission
    url: https://idr.openmicroscopy.org/about/submission.html
  - name: IDR Analysis
    url: https://idr-analysis.openmicroscopy.org
  - name: IDR Jupyter
    url: https://idr.openmicroscopy.org/jupyter
  - name: IDR (well 590686)
    url: https://idr.openmicroscopy.org/webclient/?show=well-590686
  - name: IDR (well 119093)
    url: https://idr.openmicroscopy.org/webclient/?show=well-119093
  - name: IDR (well 4852)
    url: https://idr.openmicroscopy.org/webclient/?show=well-4852
  - name: IDR (well 469267)
    url: https://idr.openmicroscopy.org/webclient/?show=well-469267
  - name: IDR (well 547609)
    url: https://idr.openmicroscopy.org/webclient/?show=well-547609
  - name: IDR (image 820684)
    url: https://idr.openmicroscopy.org/webclient/?show=image-820684
  - name: IDR (well 37472)
    url: https://idr.openmicroscopy.org/webclient/?show=well-37472
  - name: IDR (well 45407)
    url: https://idr.openmicroscopy.org/webclient/?show=well-45407
  - name: IDR (image 648950)
    url: https://idr.openmicroscopy.org/webclient/?show=image-648950
  - name: IDR (image 3063667)
    url: https://idr.openmicroscopy.org/webclient/?show=image-3063667
  - name: IDR (image 2849866)
    url: https://idr.openmicroscopy.org/webclient/?show=image-2849866
  - name: IDR (image 1821818)
    url: https://idr.openmicroscopy.org/webclient/?show=image-1821818
  - name: IDR (image 1636543)
    url: https://idr.openmicroscopy.org/webclient/?show=image-1636543
  - name: IDR (well 1056578)
    url: https://idr.openmicroscopy.org/webclient/?show=well-1056578
  - name: IDR (well 1029401)
    url: https://idr.openmicroscopy.org/webclient/?show=well-1029401
  - name: IDR (well 1046336)
    url: https://idr.openmicroscopy.org/webclient/?show=well-1046336
  - name: IDR (dataset 369)
    url: https://idr.openmicroscopy.org/webclient/?show=dataset-369
  - name: IDR (well 1024671)
    url: https://idr.openmicroscopy.org/webclient/?show=well-1024671
  - name: IDR (well 1030579)
    url: https://idr.openmicroscopy.org/webclient/?show=well-1030579
  - name: IDR (dataset 51)
    url: https://idr.openmicroscopy.org/webclient/?show=dataset-51
  - name: IDR (dataset 61)
    url: https://idr.openmicroscopy.org/webclient/?show=dataset-61
  - name: IDR 2858266
    url: https://idr.openmicroscopy.org/webclient/?show=image-2858266
  - name: IDR (image 2895051)
    url: https://idr.openmicroscopy.org/webclient/?show=image-2895051
  - name: IDR (image 3125776)
    url: https://idr.openmicroscopy.org/webclient/?show=image-3125776
  - name: IDR (phenotype CMPO_0000393)
    url: https://idr.openmicroscopy.org/mapr/phenotype/?value=CMPO_0000393
  - name: IDR (phenotype CMPO_0000118)
    url: https://idr.openmicroscopy.org/mapr/phenotype/?value=CMPO_0000118
  - name: IDR (phenotype CMPO_0000140)
    url: https://idr.openmicroscopy.org/mapr/phenotype/?value=CMPO_0000140
  - name: IDR (gene SGOL1)
    url: https://idr.openmicroscopy.org/mapr/gene/?value=SGOL1
  - name: IDR (gene Car4)
    url: https://idr.openmicroscopy.org/mapr/gene/?value=Car4
  - name: IDR (dataset 153)
    url: https://idr.openmicroscopy.org/webclient/?show=dataset-153
  - name: IDR (image 1918940)
    url: https://idr.openmicroscopy.org/webclient/?show=image-1918940
  - name: IDR (image 1918953)
    url: https://idr.openmicroscopy.org/webclient/?show=image-1918953
  - name: IDR (well 828419)
    url: https://idr.openmicroscopy.org/webclient/?show=well-828419
  - name: IDR (mineotaur)
    url: https://idr.openmicroscopy.org/mineotaur/
  - name: IDR (well 592371)
    url: https://idr.openmicroscopy.org/webclient/?show=well-592371
  - name: IDR notebooks (GitHub)
    url: https://github.com/IDR/idr-notebooks
  - name: IDR metadat (GitHub)
    url: https://github.com/IDR/idr-metadata


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: /status
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/ome/www.openmicroscopy.org/master/img/logos/ome.svg
  name: OME status
  introTitle: "Welcome to the status page of OME services"
  introMessage: Contact OME on the [image.sc](https://forum.image.sc/) forum or [Twitter](https://twitter.com/openmicroscopy) to report issues
  navbar:
    - title: Status
      href: /status
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
