# Change these first
owner: ome # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: OME website
    url: https://www.openmicroscopy.org
  - name: OME website (alias)
    url: https://openmicroscopy.org
  - name: OME website (legacy)
    url: https://www-legacy.openmicroscopy.org
  - name: OME blog (redirected)
    url: https://blog.openmicroscopy.org
  - name: OME NGFF
    url: https://ngff.openmicroscopy.org
  - name: OME forum (legacy)
    url: https://phpbb.openmicroscopy.org
  - name: OMERO figure static website (redirected)
    url: https://figure.openmicroscopy.org
  - name: OME help (redirected)
    url: https://help.openmicroscopy.org
  - name: OME contributing
    url: https://ome-contributing.readthedocs.io/en/latest/
  - name: OME contributing (redirected)
    url: https://www.openmicroscopy.org/site/support/contributing/
  - name: OME artifactory
    url: https://artifacts.openmicroscopy.org
  - name: OME downloads
    url: https://downloads.openmicroscopy.org
  - name: OME documentation
    url: https://docs.openmicroscopy.org
  - name: OME demo server
    url: https://demo.openmicroscopy.org
  - name: OME XSD schemas
    url: http://www.openmicroscopy.org/Schemas
  - name: OME CI server (legacy)
    url: https://ci.openmicroscopy.org
  - name: OME CI server (merge)
    url: https://merge-ci.openmicroscopy.org/jenkins
  - name: OME CI server (latest)
    url: https://latest-ci.openmicroscopy.org/jenkins
  - name: OME training server 1
    url: https://outreach.openmicroscopy.org
  - name: OME issue tracking system (legacy)
    url: https://trac.openmicroscopy.org
  # Number of redirects hit maximum amount
  # - name: OME trac OMERO API (redirected)
  #   url: https://trac.openmicroscopy.org.uk/ome/wiki/OmeroApi
  - name: OME file formats (redirected)
    url: http://www.openmicroscopy.org/site/support/file-formats
  - name: OME units documentation (redirected)
    url:  https://www.openmicroscopy.org/site/support/ome-model/developers/ome-units.html
  - name: OME training server 2
    url: https://workshop.openmicroscopy.org
  - name: OME Q&A
    url: http://qa.openmicroscopy.org.uk/
  - name: OME gate (22)
    check: "tcp-ping"
    url: $OME_GATE
    port: 22
  - name: OME gate (443)
    check: "tcp-ping"
    url: $OME_GATE
    port: 443
  - name: UoD SLS OMERO (authenticated)
    url: https://nightshade.openmicroscopy.org
  - name: UoD SLS OMERO (4063)
    check: "tcp-ping"
    url: nightshade.openmicroscopy.org
    port: 4063
  - name: UoD SLS OMERO (4064)
    check: "tcp-ping"
    url: nightshade.openmicroscopy.org
    port: 4064
  - name: UoD SLS OMERO (public)
    url: https://omero.lifesci.dundee.ac.uk
  - name: UoD SLS OMERO (image 3925540 - render_thumbnail)
    url: https://omero.lifesci.dundee.ac.uk/webgateway/render_thumbnail/3925540/
  - name: UoD SLS OMERO (image 3925540 - render_image)
    url: https://omero.lifesci.dundee.ac.uk/webgateway/render_image/3925540/3/5/
  - name: UoD SLS OMERO (image 3925540 - img_detail)
    url: https://omero.lifesci.dundee.ac.uk/webgateway/img_detail/3925540/
  - name: UoD SLS OMERO (10.17867/10000109)
    url: http://dx.doi.org/10.17867/10000109
  - name: UoD teaching OMERO
    url: https://learning.openmicroscopy.org

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: /status
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/ome/www.openmicroscopy.org/master/img/logos/ome.svg
  name: OME status
  introTitle: "Welcome to the status page of OME services"
  introMessage: Contact OME on the [image.sc](https://forum.image.sc/tag/ome) forum or [Twitter](https://twitter.com/openmicroscopy) to report issues
  navbar:
    - title: IDR Status
      href: https://idr.github.io/upptime
    - title: GitHub Status
      href: https://www.githubstatus.com/
    - title: GitHub repository
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
