# Change these first
owner: sbesson # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: OME website
    url: https://www.openmicroscopy.org
  - name: OME website (alias)
    url: https://openmicroscopy.org
  - name: OME website (legacy)
    url: https://www-legacy.openmicroscopy.org
  - name: OME blog
    url: https://blog.openmicroscopy.org
  - name: OME artifactory
    url: https://artifacts.openmicroscopy.org
  - name: OME downloads
    url: https://downloads.openmicroscopy.org
  - name: OME documentation
    url: https://docs.openmicroscopy.org
  - name: OME demo server
    url: https://demo.openmicroscopy.org
  - name: OME XSD schemas
    url: http://www.openmicroscopy.org/Schemas
  - name: OME CI server (legacy)
    url: https://ci.openmicroscopy.org
  - name: OME CI server (merge)
    url: https://merge-ci.openmicroscopy.org/jenkins
  - name: OME CI server (latest)
    url: https://latest-ci.openmicroscopy.org/jenkins
  - name: OME training server 1
    url: https://outreach.openmicroscopy.org
  - name: OME issue tracking system (legacy)
    url: https://trac.openmicroscopy.org
  - name: OME training server 2
    url: https://workshop.openmicroscopy.org
  - name: OME GitHub
    url: https://github.com/ome
  - name: UoD SLS research OMERO
    url: https://nightshade.openmicroscopy.org
  - name: UoD SLS research OMERO (public)
    url: https://omero.lifesci.dundee.ac.uk
  - name: UoD teaching OMERO
    url: https://learning.openmicroscopy.org
  - name: UoD teaching OMERO
    url: https://learning.openmicroscopy.org
  - name: IDR
    url: https://idr.openmicroscopy.org
  - name: IDR FTP
    check: "tcp-ping"
    url: idr-ftp.openmicroscopy.org
    port: 21
  - name: ITR
    url: https://itr.openmicroscopy.org
  - name: IDR API
    url: https://idr.openmicroscopy.org/about/api.html
  - name: IDR submission
    url: https://idr.openmicroscopy.org/about/submission.html
  - name: IDR Analysis
    url: https://idr-analysis.openmicroscopy.org
  - name: IDR Jupyter
    url: https://idr.openmicroscopy.org/jupyter

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: /status
  # baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/ome/www.openmicroscopy.org/master/img/logos/ome.svg
  name: OME status
  introTitle: "Welcome to the status page of OME services"
  introMessage: Contact OME on the [image.sc](https://forum.image.sc/) forum or [Twitter](https://twitter.com/openmicroscopy) to report issues
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
